# Generated by Django 5.1 on 2024-09-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='n_questions',
            field=models.IntegerField(default=12),
        ),
    ]
