# Generated by Django 5.1 on 2024-09-07 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pseudouser_psudouseranswer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='GroupExp',
        ),
    ]
