# Generated by Django 5.1 on 2024-09-07 20:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_group_groupexp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psudouseranswer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='useringroup',
            name='group',
        ),
        migrations.RemoveField(
            model_name='useringroup',
            name='user',
        ),
        migrations.AddField(
            model_name='groupexp',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_in_group', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='pseudoUser',
        ),
        migrations.DeleteModel(
            name='psudoUserAnswer',
        ),
        migrations.DeleteModel(
            name='UserInGroup',
        ),
    ]
